m = 0.1; %kg
theta_0 = 0.05; %rad
theta_0_dot = 0.01; %rad/s
l0 = 20; %meters
r0 = 22; %meters
r0_dot = 0.1; % m/s
k = 20; %N/m
g = 9.8; %m/s2
x(1) = 1.1;
y(1) = -22;
x_dot0 = 1.15;
y_dot0 = 0.155;
dt = 0.0001;
y(2) = y(1)+y_dot0*dt;
x(2) = x(1)+x_dot0*dt;
t = 0:dt:10;
for i = 2:length(t)-1
    current = i;
    l = sqrt(x(i).^2+y(i).^2);
    x_prev = x(i-1);
    y_prev = y(i-1);
    x_cur = x(i);
    y_cur = y(i);
    f_x = @(x_new)((x_new-2*x_cur+x_prev)/(dt^2)+l0*x_cur/(m*l)+x_cur*k/m);
    f_y = @(y_new)((y_new-2*y_cur+y_prev)/(dt^2)+k*y_cur/m*(1-l0/l)+g);
    x_new = fzero(f_x,x_cur);
    y_new = fzero(f_y, y_cur);
    x(i+1) = x_new;
    y(i+1) = y_new;
end
plot(x,y);